var cloudinary = require('cloudinary').v2;
cloudinary.config({ 
  cloud_name: 'dljgmfj95', 
  api_key: '467489591245219', 
  api_secret: '8h0hDjpDDt2wyhgTPr_gJJCusXY' 
});

cloudinary.uploader.upload('./assets/memories/torgersen_bridge.jpg', { tags: 'torgerson_bridge' }, function (err, image) {
    console.log();
    console.log("** File Upload");
    if (err) { console.warn(err); }
    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
    console.log("* " + image.public_id);
    console.log("* " + image.url);
    // waitForAllUploads("pizza", err, image);
  });